version: '3.8'

services:
  i6shark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i6shark
    restart: unless-stopped
    network_mode: "host"  # Need host network for IPv6 manipulation
    cap_add:
      - NET_ADMIN  # Required for IPv6 address management
    environment:
      - SHARED_SECRET=${SHARED_SECRET:-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
      - IPV6_PREFIX=${IPV6_PREFIX:-xxxx:xxxx:xxxx}
      - IPV6_SUBNET=${IPV6_SUBNET:-1000}
      - INTERFACE=${INTERFACE:-ens0}
      - LISTEN_PORT=${LISTEN_PORT:-80}
      - LISTEN_HOST=${LISTEN_HOST:-0.0.0.0}
      - DEBUG=${DEBUG:-false}
      - DESIRED_POOL_SIZE=${DESIRED_POOL_SIZE:-1000}
    volumes:
      - ./.env:/app/.env:ro  # Mount .env file (will override environment variables)
    ports:
      - "80:80" 